task:
  name: PongBotRTerrain
  physics_engine: physx
  env:
    numEnvs: ${resolve_default:4096,${...num_envs}}
    numObservations: 53
    observeSteps: 1
    numActions: 12
    numStates: 87
    envSpacing: 0.5
    enableDebugVis: false
    test: false
    terrain:
      terrainType: plane
      staticFriction: 1.0
      dynamicFriction: 1.0
      restitution: 0.5
      curriculum: true
      maxInitMapLevel: 0
      mapLength: 8.0
      mapWidth: 8.0
      numLevels: 10
      numTerrains: 30
      terrainProportions:
      - 0.2
      - 0.2
      - 0.15
      - 0.2
      - 0.18
      slopeTreshold: 0.25
    baseInitState:
      pos:
      - 0.0
      - 0.0
      - 0.56
      rot:
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      vLinear:
      - 0.0
      - 0.0
      - 0.0
      vAngular:
      - 0.0
      - 0.0
      - 0.0
    randomCommandVelocityRanges:
      linear_x:
      - -0.5
      - 0.5
      linear_y:
      - -0.5
      - 0.5
      yaw:
      - -1.57
      - 1.57
    EnvsNumRanges:
      stand_env_range: 200
      only_plus_x_envs_range: 200
      only_minus_x_envs_range: 200
      only_plus_y_envs_range: 200
      only_minus_y_envs_range: 200
      only_plus_yaw_envs_range: 200
      only_minus_yaw_envs_range: 200
      plus_x_plus_yaw_envs_range: 200
      plus_x_minus_yaw_envs_range: 200
      minus_x_plus_yaw_envs_range: 200
      minus_x_minus_yaw_envs_range: 200
    control:
      stiffness: 450.0
      damping: 9.0
      actionScale: 0.5
      decimation: 4
    defaultJointAngles:
      FL_HR_JOINT: 0.0
      FR_HR_JOINT: 0.0
      RL_HR_JOINT: 0.0
      RR_HR_JOINT: 0.0
      FL_HP_JOINT: 0.75
      FR_HP_JOINT: 0.75
      RL_HP_JOINT: 0.75
      RR_HP_JOINT: 0.75
      FL_KN_JOINT: -1.5
      FR_KN_JOINT: -1.5
      RL_KN_JOINT: -1.5
      RR_KN_JOINT: -1.5
    urdfAsset:
      file: urdf/PongBot_R_V1/urdf/PongBot_R_V1_(train).urdf
      test_file: urdf/PongBot_R_V1/urdf/PongBot_R_V1_(train).urdf
      footName: TIP
      calfName: CALF
      collapseFixedJoints: false
      fixBaseLink: false
      defaultDofDriveMode: 4
    learn:
      addNoise: true
      noiseLevel: 1.25
      dofPositionNoise: 0.025
      dofVelocityNoise: 2.0
      angularVelocityNoise: 0.3
      gravityNoise: 0.05
      heightMeasurementNoise: 0.06
      allowcalfContacts: true
      soft_dof_pos_limit: 0.9
      reward:
        rew_ang_vel_z: 1.0
        rew_lin_vel_xy: 1.5
        penalty_lin_vel_z: -0.0
        penalty_ang_vel_xy: -0.0
        penalty_base_acc: -0.0
        penalty_base_ori: -2.0
        penalty_base_height: -2.0
        penalty_collision: -0.075
        penalty_roll_pos: -0.25
        penalty_slip: -0.25
        penalty_num_contact_feet: -0.0
        penalty_zero_contact_feet: -0.0
        penalty_default_num_contact_feet: -0.25
        penalty_foot_height: -2.0
        penalty_short_swing: -0.0
        penalty_global_foot_xy_forces: -0.0
        penalty_swing_stance_phase: -0.005
        penalty_dof_pos_limits: -3.5
        penalty_default_pos_hp: -0.25
        penalty_default_pos_knp: -0.25
        penalty_default_pos_standing: -1.0
        penalty_zero_vel_standing: -0.0
        penalty_trot_pitch: -0.0
        penalty_foot_contact_force: -0.0
        penalty_base_foot_xy_pos: -0.0
        penalty_default_grf: -0.005
        penalty_dof_acc_zero_crossing: -0.0
        penalty_torques: -0.0001
        penalty_over_nominal: -0.0001
        penalty_action_smoothness1: -0.0025
        penalty_action_smoothness2: -0.0025
        penalty_joint_vel: -0.0045
        penalty_actions: -0.05
      obs_scales:
        dofPositionScale: 1.0
        dofVelocityScale: 0.1
        angularVelocityScale: 0.25
      randomizeFriction: true
      frictionRange:
      - 0.5
      - 1.25
      pushRobots: true
      pushInterval_s: 14
      cmdInterval_s: 13
      zerocmdInterval_s: 10
      freezecmdInterval_s: 30
      episodeLength_s: 20
    viewer:
      refEnv: 0
      pos:
      - 0
      - 0
      - 10
      lookat:
      - 1.0
      - 1
      - 9
    enableCameraSensors: false
  sim:
    dt: 0.002
    substeps: 1
    up_axis: z
    use_gpu_pipeline: ${eq:${...pipeline},"gpu"}
    gravity:
    - 0.0
    - 0.0
    - -9.81
    physx:
      num_threads: ${....num_threads}
      solver_type: ${....solver_type}
      use_gpu: ${contains:"cuda",${....sim_device}}
      num_position_iterations: 6
      num_velocity_iterations: 1
      contact_offset: 0.02
      rest_offset: 0.0
      bounce_threshold_velocity: 0.2
      max_depenetration_velocity: 100.0
      default_buffer_size_multiplier: 5.0
      max_gpu_contact_pairs: 8388608
      num_subscenes: ${....num_subscenes}
      contact_collection: 1
  task:
    randomize: true
    randomization_params:
      frequency: 500
      observations:
        range:
        - 0
        - 0.05
        operation: additive
        distribution: gaussian
      actions:
        range:
        - 0.0
        - 0.05
        operation: additive
        distribution: gaussian
      sim_params:
        gravity:
          range:
          - 0
          - 0.05
          operation: additive
          distribution: gaussian
          schedule: quadratic
          schedule_steps: 100
      actor_params:
        pongbotr:
          rigid_body_properties:
            mass:
              range:
              - 0.75
              - 1.25
              operation: scaling
              distribution: uniform
              setup_only: true
              schedule: linear
              schedule_steps: 100
          rigid_shape_properties:
            friction:
              num_buckets: 500
              range:
              - 0.0
              - 0.0
              operation: additive
              distribution: uniform
              schedule: linear
              schedule_steps: 100
            restitution:
              range:
              - 0.0
              - 0.7
              operation: scaling
              distribution: uniform
              schedule: linear
              schedule_steps: 100
          dof_properties:
            damping:
              range:
              - 0.5
              - 1.5
              operation: scaling
              distribution: uniform
              schedule: linear
              schedule_steps: 200
            stiffness:
              range:
              - 0.75
              - 1.25
              operation: scaling
              distribution: uniform
              schedule: linear
              schedule_steps: 100
            lower:
              range:
              - -0.05
              - 0.05
              operation: additive
              distribution: gaussian
              schedule: linear
              schedule_steps: 100
            upper:
              range:
              - -0.05
              - 0.05
              operation: additive
              distribution: gaussian
              schedule: linear
              schedule_steps: 100
            friction:
              range:
              - 0.0
              - 0.0001
              operation: additive
              distribution: uniform
              schedule: linear
              schedule_steps: 200
            armature:
              range:
              - 0.0
              - 0.0001
              operation: additive
              distribution: uniform
              schedule: linear
              schedule_steps: 100
train:
  params:
    seed: ${...seed}
    algo:
      name: a2c_continuous
    model:
      name: continuous_a2c_logstd
    network:
      name: estimator_net
      builder:
        name: estimator_builder
      estimator: layers[64]
      separate: false
      space:
        continuous:
          mu_activation: None
          sigma_activation: None
          mu_init:
            name: default
          sigma_init:
            name: const_initializer
            val: 0.0
          fixed_sigma: true
      mlp:
        units:
        - 512
        - 256
        - 128
        activation: elu
        d2rl: false
        initializer:
          name: default
        regularizer:
          name: None
    load_checkpoint: ${if:${...checkpoint},True,False}
    load_path: ${...checkpoint}
    config:
      name: ${resolve_default:PongBotRerrain,${....experiment}}
      full_experiment_name: ${.name}
      env_name: rlgpu
      ppo: true
      multi_gpu: ${....multi_gpu}
      mixed_precision: true
      normalize_input: true
      normalize_value: true
      normalize_advantage: true
      value_bootstrap: true
      clip_actions: false
      num_actors: ${....task.env.numEnvs}
      reward_shaper:
        scale_value: 1.0
      gamma: 0.99
      tau: 0.95
      e_clip: 0.2
      entropy_coef: 0.001
      learning_rate: 0.0003
      lr_schedule: adaptive
      kl_threshold: 0.008
      truncate_grads: true
      grad_norm: 1.0
      horizon_length: 24
      minibatch_size: 16384
      mini_epochs: 5
      critic_coef: 2
      clip_value: true
      seq_len: 4
      bounds_loss_coef: 0.0
      estimator_coef: 1.0
      max_epochs: ${resolve_default:50000,${....max_iterations}}
      save_best_after: 100
      score_to_win: 20000
      save_frequency: 50
      print_stats: true
pbt:
  enabled: false
task_name: ${task.name}
experiment: ''
num_envs: ''
seed: 42
torch_deterministic: false
max_iterations: ''
physics_engine: physx
pipeline: gpu
sim_device: cuda:0
rl_device: cuda:0
graphics_device_id: 0
num_threads: 4
solver_type: 1
num_subscenes: 4
test: false
checkpoint: ''
sigma: ''
multi_gpu: false
wandb_activate: false
wandb_group: ''
wandb_name: ${train.params.config.name}
wandb_entity: ''
wandb_project: isaacgymenvs
wandb_tags: []
wandb_logcode_dir: ''
capture_video: false
capture_video_freq: 1464
capture_video_len: 100
force_render: true
headless: false
