controller_joint_names: ['', 'FL_HR_JOINT', 'FL_HP_JOINT', 'FL_KN_JOINT', 'FR_HR_JOINT', 'FR_HP_JOINT', 'FR_KN_JOINT', 'RL_HR_JOINT', 'RL_HP_JOINT', 'RL_KN_JOINT', 'RR_HR_JOINT', 'RR_HP_JOINT', 'RR_KN_JOINT', ]
